### ISSUE TITLE
Install charts from OCI registries

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#115]
Helm still doesn't support this functionality. https://github.com/helm/helm/issues/6990
We can override this behavior with native `helm pull` and `helm save` to mktemp dir.

**Comment by zhilyaev** [comment]
```
releases:
  - name: my
    chart: 'oci://localhost:5000/my/helm'
```

**Comment by r3nic1e** [comment]
I've tried implement but faced severe issue.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21b2223]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart(0x0, 0xc004c9ce60, 0xc004c9ce60, 0x0, 0x0)
	/Users/r3nic1e/go/pkg/mod/helm.sh/helm/v3@v3.5.0/internal/experimental/registry/client.go:156 +0x183
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc0015aec80, 0xc00153d5c0, 0x18, 0xc001e10d88, 0xc00153d5c0, 0x18)
	/Users/r3nic1e/go/pkg/mod/helm.sh/helm/v3@v3.5.0/pkg/getter/ocigetter.go:52 +0xc7
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc0015aec80, 0xc00153d5c0, 0x18, 0xc000b6be90, 0x6, 0x6, 0xc0015aec80, 0x0, 0x0)
	/Users/r3nic1e/go/pkg/mod/helm.sh/helm/v3@v3.5.0/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc001e11108, 0xc00089a5a0, 0x18, 0xc000522db8, 0x7, 0xc000ad5840, 0x3f, 0x0, 0x203000, 0x203000, ...)
	/Users/r3nic1e/go/pkg/mod/helm.sh/helm/v3@v3.5.0/pkg/downloader/chart_downloader.go:99 +0x142
helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc000ad15f0, 0xc00089a5a0, 0x18, 0x0, 0x0, 0x0, 0x0)
	/Users/r3nic1e/go/pkg/mod/helm.sh/helm/v3@v3.5.0/pkg/action/pull.go:128 +0x437
github.com/helmwave/helmwave/pkg/release.(*Chart).downloadOCI(0xc0001b3390, 0x18, 0xc000878630, 0x0, 0x0)
	/Users/r3nic1e/git/helmwave/helmwave/pkg/release/chart.go:66 +0x1df
```

This happens because of uninitialized `RegistryClient` in `action.Configuration` struct. `RegistryClient` is stored in private package `helm.sh/helm/v3/internal/experimental/registry`, so we can't just create it.
The only place in helm that creates new client is private method, that creates cobra commands - https://github.com/helm/helm/blob/v3.5.4/cmd/helm/root.go#L156

So this feature is impossible to implement atm.

**Comment by zhilyaev** [comment]
nice https://github.com/helm/helm/pull/9200

**Comment by eshepelyuk** [comment]
Helm 3.7 is released with reworked support for OCI based charts.
Currently it uses the same helm pull, helm install as for ChartMuseum charts.

**Comment by zhilyaev** [comment]
Update for helmwave >= 0.12.0

```
releases:
  - name: my
    chart: 'oci://localhost:5000/my/helm'

```

**Comment by zhilyaev** [comment]
coming soon...
