### ISSUE TITLE
Concurrent map write in copying same values

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#182]
helmwave.yml:
```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami


.options: &options
  atomic: true
  wait: true
  timeout: 10m
  createnamespace: true
  namespace: blabla

releases:
  - name: redis-a
    <<: *options
    tags:
      - redis
      - redis-a
    chart:
      name: bitnami/redis
    values:
      - values/redis.yaml


  - name: redis-b
    <<: *options
    chart:
      name: bitnami/redis
    tags:
      - redis
      - redis-b
    values:
      - values/redis.yaml
    depends_on:
      - redis-a@blabla
```

I have two releases that use same values file. And these values get copied twice with concurrent map write:
```
❯ helmwave build
[🙃 aka INFO]: Building releases...
[🙃 aka INFO]: Building graphs...
[🙃 aka INFO]: Depends On:
┌─────────────────┐   ┌─────────────────┐
│ redis-b@blabla  ├───┤ redis-a@blabla  │
└─────────────────┘   └─────────────────┘

[🙃 aka INFO]: Building values...
[🤷 aka DEBUG]: Loading sprig template functions
[🤷 aka DEBUG]: Loading sprig template functions
[🙃 aka INFO]: ✅ redis-b@blabla values count 1
	values:
	  - /var/folders/85/_0y1yy092cxb0b4s2rg5tqd00000gn/T/.helmwave/1638431101/values/redis-b@blabla/6cb757e92b4939c2dfaa5e55bcafee9267666f22.yml
[🙃 aka INFO]: ✅ redis-a@blabla values count 1
	values:
	  - /var/folders/85/_0y1yy092cxb0b4s2rg5tqd00000gn/T/.helmwave/1638431101/values/redis-a@blabla/6cb757e92b4939c2dfaa5e55bcafee9267666f22.yml
[🙃 aka INFO]: Building repositories...
[🤷 aka DEBUG]: 🗄 repo dependencies
	bitnami:
	  - redis-a@blabla
	  - redis-b@blabla
[🙃 aka INFO]: 🗄 "bitnami" has been added to the plan
[🙃 aka INFO]: ❎  "bitnami" already exists with the same configuration, skipping
[🙃 aka INFO]: Building manifests...
[🙈 aka WARNING]: ❌ redis-b@blabla cant get dependencies : could not find bitnami/redis: stat bitnami/redis: no such file or directory
[🙈 aka WARNING]: ❌ redis-a@blabla cant get dependencies : could not find bitnami/redis: stat bitnami/redis: no such file or directory
[🤷 aka DEBUG]: 📄 "redis-a@blabla" template manifest
[🤷 aka DEBUG]: 📄 "redis-b@blabla" template manifest
fatal error: concurrent map writes

goroutine 15 [running]:
runtime.throw({0x3845028, 0x10})
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1198 +0x71 fp=0xc0029bfde8 sp=0xc0029bfdb8 pc=0x10340b1
runtime.mapassign_faststr(0xc000648000, 0x48ff, {0xc000919310, 0xe})
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/map_faststr.go:211 +0x39c fp=0xc0029bfe50 sp=0xc0029bfde8 pc=0x1012d5c
github.com/helmwave/helmwave/pkg/plan.(*Plan).buildManifest.func1(0xc00004c5a0, 0xc000250180)
	/home/runner/work/helmwave/helmwave/pkg/plan/build_manifests.go:45 +0x593 fp=0xc0029bffc0 sp=0xc0029bfe50 pc=0x2f45d73
github.com/helmwave/helmwave/pkg/plan.(*Plan).buildManifest·dwrap·8()
	/home/runner/work/helmwave/helmwave/pkg/plan/build_manifests.go:48 +0x31 fp=0xc0029bffe0 sp=0xc0029bffc0 pc=0x2f457b1
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0029bffe8 sp=0xc0029bffe0 pc=0x1064d41
created by github.com/helmwave/helmwave/pkg/plan.(*Plan).buildManifest
	/home/runner/work/helmwave/helmwave/pkg/plan/build_manifests.go:16 +0x6d

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x20)
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x103ee0e)
	/opt/hostedtoolcache/go/1.17.3/x64/src/sync/waitgroup.go:130 +0x71
github.com/helmwave/helmwave/pkg/parallel.(*WaitGroup).Wait(0xc00004c5a0)
	/home/runner/work/helmwave/helmwave/pkg/parallel/parallel.go:40 +0x3f
github.com/helmwave/helmwave/pkg/plan.(*Plan).buildManifest(0xc0000a42d0)
	/home/runner/work/helmwave/helmwave/pkg/plan/build_manifests.go:51 +0x154
github.com/helmwave/helmwave/pkg/plan.(*Plan).Build(0xc0000a42d0, {0x382d950, 0xc00011f338}, {0x582d6e8, 0x0, 0x0}, 0x68)
	/home/runner/work/helmwave/helmwave/pkg/plan/build.go:53 +0x378
github.com/helmwave/helmwave/pkg/action.(*Build).Run(0xc00031b0e0)
	/home/runner/work/helmwave/helmwave/pkg/action/build.go:38 +0xba
github.com/helmwave/helmwave/pkg/action.(*Build).Cmd.func1(0xc000bcc3c0)
	/home/runner/work/helmwave/helmwave/pkg/action/interface.go:13 +0x1b
github.com/urfave/cli/v2.(*Command).Run(0xc000bc2ea0, 0xc000b92bc0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000703520, {0x3d3a210, 0xc000132008}, {0xc000136000, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/runner/work/helmwave/helmwave/cmd/helmwave/main.go:46 +0x549

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xfb

goroutine 39 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0004ee200)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92

goroutine 13 [chan receive]:
github.com/helmwave/helmwave/pkg/parallel.(*WaitGroup).gatherErrors(0xc00004c5a0)
	/home/runner/work/helmwave/helmwave/pkg/parallel/parallel.go:34 +0xa8
created by github.com/helmwave/helmwave/pkg/parallel.NewWaitGroup
	/home/runner/work/helmwave/helmwave/pkg/parallel/parallel.go:26 +0xfe

goroutine 14 [runnable]:
runtime.CallersFrames(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/symtab.go:66
github.com/sirupsen/logrus.getCaller()
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:200 +0x9b
github.com/sirupsen/logrus.(*Entry).log(0xc002e2bde0, 0x4, {0xc003f97fc0, 0x20})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:238 +0x167
github.com/sirupsen/logrus.(*Entry).Log(0xc000277960, 0x4, {0xc002e2bde0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Logf(0xc000277960, 0x4, {0x384330c, 0xc002e2be40}, {0xc002e2bf08, 0x10, 0x316aba0})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0x85
github.com/sirupsen/logrus.(*Logger).Logf(0xc000164850, 0x4, {0x384330c, 0x14}, {0xc002e2bf08, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:151 +0x85
github.com/sirupsen/logrus.(*Logger).Infof(...)
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:165
github.com/sirupsen/logrus.Infof(...)
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/exported.go:199
github.com/helmwave/helmwave/pkg/plan.(*Plan).buildManifest.func1(0xc00004c5a0, 0xc000250000)
	/home/runner/work/helmwave/helmwave/pkg/plan/build_manifests.go:47 +0x695
created by github.com/helmwave/helmwave/pkg/plan.(*Plan).buildManifest
	/home/runner/work/helmwave/helmwave/pkg/plan/build_manifests.go:16 +0x6d

goroutine 52 [IO wait]:
internal/poll.runtime_pollWait(0xfa8ddf0, 0x72)
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00014a280, 0xc002238000, 0x0)
	/opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00014a280, {0xc002238000, 0x10d98, 0x10d98})
	/opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00014a280, {0xc002238000, 0x4d56, 0xc001e8d040})
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00374e028, {0xc002238000, 0x1350d79, 0xc01985e7f8})
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc003a5efd8, {0xc002238000, 0x0, 0x100964d})
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00011e978, {0x3ce8080, 0xc003a5efd8})
	/opt/hostedtoolcache/go/1.17.3/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00011e700, {0xfa8e010, 0xc00374e028}, 0xc002244047)
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00011e700, 0x0)
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00011e700, {0xc001fd2000, 0x1000, 0xc0006824e0})
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc001f7c120, {0xc001e3bd18, 0x9, 0xc004352780})
	/opt/hostedtoolcache/go/1.17.3/x64/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x3ce7da0, 0xc001f7c120}, {0xc001e3bd18, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.17.3/x64/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/io/io.go:347
net/http.http2readFrameHeader({0xc001e3bd18, 0x9, 0xc001f5aed0}, {0x3ce7da0, 0xc001f7c120})
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:1555 +0x6e
net/http.(*http2Framer).ReadFrame(0xc001e3bce0)
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:1813 +0x95
net/http.(*http2clientConnReadLoop).run(0xc01985ef98)
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:8583 +0x130
net/http.(*http2ClientConn).readLoop(0xc000369200)
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:8506 +0x6f
created by net/http.(*http2Transport).newClientConn
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:7317 +0xb85

goroutine 68 [IO wait]:
internal/poll.runtime_pollWait(0xfa8ded8, 0x72)
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00091e280, 0xc001b40000, 0x0)
	/opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00091e280, {0xc001b40000, 0xc2b5, 0xc2b5})
	/opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00091e280, {0xc001b40000, 0xc001b43007, 0x1a})
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00000e058, {0xc001b40000, 0x1350d79, 0xc004f757f8})
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000b8ed80, {0xc001b40000, 0x0, 0x100964d})
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00044be78, {0x3ce8080, 0xc000b8ed80})
	/opt/hostedtoolcache/go/1.17.3/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00044bc00, {0xfa8e010, 0xc00000e058}, 0x92b3)
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00044bc00, 0x0)
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00044bc00, {0xc00205e000, 0x1000, 0xc0007824e0})
	/opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc004353d40, {0xc002078038, 0x9, 0xc004352660})
	/opt/hostedtoolcache/go/1.17.3/x64/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x3ce7da0, 0xc004353d40}, {0xc002078038, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.17.3/x64/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/io/io.go:347
net/http.http2readFrameHeader({0xc002078038, 0x9, 0xc006332cf0}, {0x3ce7da0, 0xc004353d40})
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:1555 +0x6e
net/http.(*http2Framer).ReadFrame(0xc002078000)
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:1813 +0x95
net/http.(*http2clientConnReadLoop).run(0xc004f75f98)
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:8583 +0x130
net/http.(*http2ClientConn).readLoop(0xc0001e2d80)
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:8506 +0x6f
created by net/http.(*http2Transport).newClientConn
	/opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:7317 +0xb85
```

**Comment by zhilyaev** [comment]
Do you @r-mironov wanna fix it?

**Comment by r-mironov** [comment]
> Do you @r-mironov wanna fix it? 

Yep, wanna try to fix it

**Comment by r-mironov** [comment]
@r3nic1e @zhilyaev

I cant reproduce a bug:
```
╰─$ HELMWAVE_LOG_LEVEL=debug ./helmwave-0-16-2 build                                     
[🙃 aka INFO]: Building releases...
[🙃 aka INFO]: Building graphs...
[🙃 aka INFO]: Depends On:
┌─────────────────┐   ┌─────────────────┐
│ redis-b@blabla  ├───┤ redis-a@blabla  │
└─────────────────┘   └─────────────────┘

[🙃 aka INFO]: Building values...
[🤷 aka DEBUG]: Loading sprig template functions
[🤷 aka DEBUG]: Loading sprig template functions
[🙃 aka INFO]: ✅ redis-b@blabla values count 1
        values: 
          - /var/folders/mk/9dn0q4yx5ld5_1qmp3hl8yn0k95pm2/T/.helmwave/1638825893/values/redis-b@blabla/6cb757e92b4939c2dfaa5e55bcafee9267666f22.yml
[🙃 aka INFO]: ✅ redis-a@blabla values count 1
        values: 
          - /var/folders/mk/9dn0q4yx5ld5_1qmp3hl8yn0k95pm2/T/.helmwave/1638825893/values/redis-a@blabla/6cb757e92b4939c2dfaa5e55bcafee9267666f22.yml
[🙃 aka INFO]: Building repositories...
[🤷 aka DEBUG]: 🗄 repo dependencies
        bitnami: 
          - redis-a@blabla
          - redis-b@blabla
[🙃 aka INFO]: 🗄 "bitnami" has been added to the plan
[🙃 aka INFO]: ❎  "bitnami" already exists with the same configuration, skipping
[🙃 aka INFO]: Building manifests...
[🙈 aka WARNING]: ❌ redis-b@blabla cant get dependencies : could not find bitnami/redis: stat bitnami/redis: no such file or directory
[🙈 aka WARNING]: ❌ redis-a@blabla cant get dependencies : could not find bitnami/redis: stat bitnami/redis: no such file or directory
[🤷 aka DEBUG]: 📄 "redis-a@blabla" template manifest 
[🤷 aka DEBUG]: 📄 "redis-b@blabla" template manifest 
[🙃 aka INFO]: ✅ redis-a@blabla manifest done
[🙃 aka INFO]: ✅ redis-b@blabla manifest done
[🙃 aka INFO]: 🏗 Plan
        releases: 
          - redis-a@blabla
          - redis-b@blabla
        repositories: 
          - bitnami
[🙃 aka INFO]: 🆚 Diff manifests in the kubernetes cluster
[🙈 aka WARNING]: I cant get realease from k8s: release: not found
[🙈 aka WARNING]: I cant get realease from k8s: release: not found
[🙃 aka INFO]: 🏗 Planfile is ready!
        deploy it with next command: helmwave up --plandir .helmwave/
```

Can you provide your version of helmwave & `values/redis.yaml` content?

I also checked `ghcr.io/helmwave/helmwave:0.16.2` and there is no problem

**Comment by zhilyaev** [comment]
Can't reproduce this bug

**Comment by r3nic1e** [comment]
Concurrent write to map is still there - https://github.com/helmwave/helmwave/blob/main/pkg/plan/build_manifests.go#L45
